# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_advanced.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_plugin = QtWidgets.QGroupBox(Form)
        self.groupBox_plugin.setObjectName("groupBox_plugin")
        self.verticalLayout_plugin = QtWidgets.QVBoxLayout(self.groupBox_plugin)
        self.verticalLayout_plugin.setObjectName("verticalLayout_plugin")
        self.label_info_text = QtWidgets.QLabel(self.groupBox_plugin)
        self.label_info_text.setWordWrap(True)
        self.label_info_text.setObjectName("label_info_text")
        self.verticalLayout_plugin.addWidget(self.label_info_text)
        self.widget_auth_container = QtWidgets.QWidget(self.groupBox_plugin)
        self.widget_auth_container.setObjectName("widget_auth_container")
        self.verticalLayout_auth_items = QtWidgets.QVBoxLayout(self.widget_auth_container)
        self.verticalLayout_auth_items.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_auth_items.setObjectName("verticalLayout_auth_items")
        self.verticalLayout_plugin.addWidget(self.widget_auth_container)
        self.widget_btn_auth = QtWidgets.QWidget(self.groupBox_plugin)
        self.widget_btn_auth.setObjectName("widget_btn_auth")
        self.horizontalLayout_btn_auth = QtWidgets.QHBoxLayout(self.widget_btn_auth)
        self.horizontalLayout_btn_auth.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_btn_auth.setObjectName("horizontalLayout_btn_auth")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn_auth.addItem(spacerItem)
        self.btn_open_auth_dialog = QtWidgets.QPushButton(self.widget_btn_auth)
        self.btn_open_auth_dialog.setMinimumSize(QtCore.QSize(220, 32))
        self.btn_open_auth_dialog.setMaximumSize(QtCore.QSize(280, 16777215))
        self.btn_open_auth_dialog.setObjectName("btn_open_auth_dialog")
        self.horizontalLayout_btn_auth.addWidget(self.btn_open_auth_dialog)
        self.verticalLayout_plugin.addWidget(self.widget_btn_auth)
        self.verticalLayout.addWidget(self.groupBox_plugin)
        self.groupBox_algo = QtWidgets.QGroupBox(Form)
        self.groupBox_algo.setObjectName("groupBox_algo")
        self.verticalLayout_algo = QtWidgets.QVBoxLayout(self.groupBox_algo)
        self.verticalLayout_algo.setObjectName("verticalLayout_algo")
        self.checkBox_filter_forever = QtWidgets.QCheckBox(self.groupBox_algo)
        self.checkBox_filter_forever.setMinimumSize(QtCore.QSize(0, 32))
        self.checkBox_filter_forever.setObjectName("checkBox_filter_forever")
        self.verticalLayout_algo.addWidget(self.checkBox_filter_forever)
        self.verticalLayout.addWidget(self.groupBox_algo)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_buttons = QtWidgets.QWidget(Form)
        self.widget_buttons.setObjectName("widget_buttons")
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout(self.widget_buttons)
        self.horizontalLayout_buttons.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_buttons.setSpacing(10)
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem1)
        self.pushButton_yes = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_yes.setMinimumSize(QtCore.QSize(100, 36))
        self.pushButton_yes.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_yes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout_buttons.addWidget(self.pushButton_yes)
        self.pushButton_no = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_no.setMinimumSize(QtCore.QSize(100, 36))
        self.pushButton_no.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_no.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout_buttons.addWidget(self.pushButton_no)
        self.verticalLayout.addWidget(self.widget_buttons)

        self.retranslateUi(Form)
        self.pushButton_no.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "高级设置"))
        self.groupBox_plugin.setTitle(_translate("Form", "插件类"))
        self.label_info_text.setText(_translate("Form", "允许插件的控制类命令后（如点击格子、重开新局等），当前局面的录像将自动标记为\"非正式\"，不计入任何排名与统计数据。各命令需要在插件管理器中完成授权后才生效。"))
        self.btn_open_auth_dialog.setText(_translate("Form", "打开插件管理器 → 控制授权"))
        self.groupBox_algo.setTitle(_translate("Form", "算法类"))
        self.checkBox_filter_forever.setToolTip(_translate("Form", "勾选后永远使用筛选法埋雷，否则会适时改用调整法"))
        self.checkBox_filter_forever.setText(_translate("Form", "永远使用筛选法埋雷（不推荐）"))
        self.pushButton_yes.setText(_translate("Form", "确定"))
        self.pushButton_yes.setShortcut(_translate("Form", "Return"))
        self.pushButton_no.setText(_translate("Form", "取消"))
