# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 269)
        Form.setMinimumSize(QtCore.QSize(580, 269))
        Form.setMaximumSize(QtCore.QSize(580, 269))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(10.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_exe = QtWidgets.QHBoxLayout()
        self.horizontalLayout_exe.setSpacing(10)
        self.horizontalLayout_exe.setObjectName("horizontalLayout_exe")
        self.label_exe = QtWidgets.QLabel(Form)
        self.label_exe.setMinimumSize(QtCore.QSize(80, 0))
        self.label_exe.setObjectName("label_exe")
        self.horizontalLayout_exe.addWidget(self.label_exe)
        self.lineEdit_exe = QtWidgets.QLineEdit(Form)
        self.lineEdit_exe.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_exe.setObjectName("lineEdit_exe")
        self.horizontalLayout_exe.addWidget(self.lineEdit_exe)
        self.pushButton_browse_exe = QtWidgets.QPushButton(Form)
        self.pushButton_browse_exe.setMinimumSize(QtCore.QSize(80, 42))
        self.pushButton_browse_exe.setMaximumSize(QtCore.QSize(80, 42))
        self.pushButton_browse_exe.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_browse_exe.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: 1px solid #999;\n"
"    border-radius: 6px;\n"
"    color: #444;\n"
"    font-weight: normal;\n"
"    font-family: \"Microsoft YaHei\", \"微软雅黑\", \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #eee;\n"
"}")
        self.pushButton_browse_exe.setObjectName("pushButton_browse_exe")
        self.horizontalLayout_exe.addWidget(self.pushButton_browse_exe)
        self.verticalLayout.addLayout(self.horizontalLayout_exe)
        self.horizontalLayout_replay = QtWidgets.QHBoxLayout()
        self.horizontalLayout_replay.setSpacing(10)
        self.horizontalLayout_replay.setObjectName("horizontalLayout_replay")
        self.label_replay = QtWidgets.QLabel(Form)
        self.label_replay.setMinimumSize(QtCore.QSize(80, 0))
        self.label_replay.setObjectName("label_replay")
        self.horizontalLayout_replay.addWidget(self.label_replay)
        self.lineEdit_replay = QtWidgets.QLineEdit(Form)
        self.lineEdit_replay.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_replay.setObjectName("lineEdit_replay")
        self.horizontalLayout_replay.addWidget(self.lineEdit_replay)
        self.pushButton_browse_file = QtWidgets.QPushButton(Form)
        self.pushButton_browse_file.setMinimumSize(QtCore.QSize(80, 42))
        self.pushButton_browse_file.setMaximumSize(QtCore.QSize(80, 42))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei,微软雅黑,Segoe UI,Arial,sans-serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_browse_file.setFont(font)
        self.pushButton_browse_file.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_browse_file.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: 1px solid #999;\n"
"    border-radius: 6px;\n"
"    color: #444;\n"
"    font-weight: normal;\n"
"    font-family: \"Microsoft YaHei\", \"微软雅黑\", \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #eee;\n"
"}")
        self.pushButton_browse_file.setObjectName("pushButton_browse_file")
        self.horizontalLayout_replay.addWidget(self.pushButton_browse_file)
        self.pushButton_browse_folder = QtWidgets.QPushButton(Form)
        self.pushButton_browse_folder.setMinimumSize(QtCore.QSize(80, 42))
        self.pushButton_browse_folder.setMaximumSize(QtCore.QSize(80, 42))
        self.pushButton_browse_folder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_browse_folder.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: 1px solid #999;\n"
"    border-radius: 6px;\n"
"    color: #444;\n"
"    font-weight: normal;\n"
"    font-family: \"Microsoft YaHei\", \"微软雅黑\", \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #eee;\n"
"}")
        self.pushButton_browse_folder.setObjectName("pushButton_browse_folder")
        self.horizontalLayout_replay.addWidget(self.pushButton_browse_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_replay)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 28))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 28))
        self.progressBar.setVisible(True)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #bbb;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    font-size: 11pt;\n"
"    height: 24px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #00A2E8;\n"
"    border-radius: 4px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.label_progress = QtWidgets.QLabel(Form)
        self.label_progress.setMinimumSize(QtCore.QSize(200, 0))
        self.label_progress.setVisible(True)
        self.label_progress.setText("")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setSpacing(10)
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ok.sizePolicy().hasHeightForWidth())
        self.pushButton_ok.setSizePolicy(sizePolicy)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(184, 51))
        self.pushButton_ok.setMaximumSize(QtCore.QSize(16777215, 51))
        self.pushButton_ok.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_ok.setAutoDefault(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_buttons.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(184, 51))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(16777215, 51))
        self.pushButton_cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_buttons.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(Form)
        self.pushButton_cancel.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "导入录像"))
        self.label_exe.setText(_translate("Form", "验证程序:"))
        self.lineEdit_exe.setPlaceholderText(_translate("Form", "选择验证程序..."))
        self.pushButton_browse_exe.setText(_translate("Form", "浏览"))
        self.label_replay.setText(_translate("Form", "录像路径:"))
        self.lineEdit_replay.setPlaceholderText(_translate("Form", "选择录像文件或文件夹..."))
        self.pushButton_browse_file.setText(_translate("Form", "选择文件"))
        self.pushButton_browse_folder.setText(_translate("Form", "选择文件夹"))
        self.pushButton_ok.setText(_translate("Form", "确认"))
        self.pushButton_ok.setShortcut(_translate("Form", "Return"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
