# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_video_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 640)
        Form.setMinimumSize(QtCore.QSize(480, 640))
        Form.setMaximumSize(QtCore.QSize(600, 640))
        Form.setSizeIncrement(QtCore.QSize(0, 0))
        Form.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 30, 20, 20)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider_time = QtWidgets.QSlider(Form)
        self.horizontalSlider_time.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider_time.setAutoFillBackground(False)
        self.horizontalSlider_time.setStyleSheet("QSlider::groove {\n"
"    border: 0px solid #bbbbbb;\n"
"    background-color: #50A6EA;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 16px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 0px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #50A6EA;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #50A6EA, stop:0.5 #87C1F1, stop:1 #50A6EA);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A6EA, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}")
        self.horizontalSlider_time.setMaximum(1000)
        self.horizontalSlider_time.setSingleStep(0)
        self.horizontalSlider_time.setPageStep(10)
        self.horizontalSlider_time.setSliderPosition(0)
        self.horizontalSlider_time.setTracking(True)
        self.horizontalSlider_time.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time.setInvertedAppearance(False)
        self.horizontalSlider_time.setInvertedControls(False)
        self.horizontalSlider_time.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_time.setTickInterval(0)
        self.horizontalSlider_time.setObjectName("horizontalSlider_time")
        self.verticalLayout.addWidget(self.horizontalSlider_time)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_replay = QtWidgets.QPushButton(self.widget)
        self.pushButton_replay.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_replay.setToolTipDuration(0)
        self.pushButton_replay.setStyleSheet("border-image: url(media/replay.svg);\n"
"QPushButton::hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"}")
        self.pushButton_replay.setText("")
        self.pushButton_replay.setObjectName("pushButton_replay")
        self.horizontalLayout.addWidget(self.pushButton_replay)
        self.pushButton_play = QtWidgets.QPushButton(self.widget)
        self.pushButton_play.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_play.setToolTipDuration(0)
        self.pushButton_play.setStyleSheet("border-image: url(media/play.svg);")
        self.pushButton_play.setText("")
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout.addWidget(self.pushButton_play)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(16, 16))
        self.label_2.setMaximumSize(QtCore.QSize(16, 16))
        self.label_2.setStyleSheet("border-image: url(media/mul.svg);\n"
"font: 12pt \"微软雅黑\";\n"
"color: #50A6EA;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_speed = SpeedLabel(self.widget)
        self.label_speed.setMinimumSize(QtCore.QSize(40, 40))
        self.label_speed.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_speed.setFont(font)
        self.label_speed.setStyleSheet("QLabel {border-image: url(media/speed.svg);\n"
"font: 16pt \"微软雅黑\";\n"
"color: #50A6EA;}")
        self.label_speed.setText("1")
        self.label_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout.addWidget(self.label_speed)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.doubleSpinBox_time = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.doubleSpinBox_time.setFont(font)
        self.doubleSpinBox_time.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"color: #50A6EA;\n"
"background-color: rgb(240, 240, 240);")
        self.doubleSpinBox_time.setWrapping(False)
        self.doubleSpinBox_time.setFrame(False)
        self.doubleSpinBox_time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_time.setDecimals(3)
        self.doubleSpinBox_time.setMinimum(-999.99)
        self.doubleSpinBox_time.setMaximum(999.99)
        self.doubleSpinBox_time.setSingleStep(0.001)
        self.doubleSpinBox_time.setObjectName("doubleSpinBox_time")
        self.horizontalLayout.addWidget(self.doubleSpinBox_time)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("QTabWidget::pane { margin: 0px; border: 0px; }\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 459))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_time = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_time.setGeometry(QtCore.QRect(0, 0, 68, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_tag = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_tag.setGeometry(QtCore.QRect(158, 0, 300, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_tag.setFont(font)
        self.label_tag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tag.setObjectName("label_tag")
        self.label_event = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_event.setGeometry(QtCore.QRect(68, 0, 90, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_event.setFont(font)
        self.label_event.setAlignment(QtCore.Qt.AlignCenter)
        self.label_event.setObjectName("label_event")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 457, 459))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_video = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_video.setGeometry(QtCore.QRect(120, 0, 271, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_video.setFont(font)
        self.label_video.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video.setObjectName("label_video")
        self.checkBox_choose = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_choose.setGeometry(QtCore.QRect(10, 0, 91, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.checkBox_choose.setFont(font)
        self.checkBox_choose.setObjectName("checkBox_choose")
        self.checkBox_choose.raise_()
        self.label_video.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.scrollArea_2.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_replay.setToolTip(_translate("Form", "重播"))
        self.pushButton_play.setToolTip(_translate("Form", "播放/暂停"))
        self.label_speed.setToolTip(_translate("Form", "滑动滚轮修改播放速度"))
        self.label_time.setText(_translate("Form", "时间"))
        self.label_tag.setText(_translate("Form", "标签"))
        self.label_event.setText(_translate("Form", "事件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "录像"))
        self.label_video.setText(_translate("Form", "录像"))
        self.checkBox_choose.setText(_translate("Form", "选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Tab 2"))
from ui.uiComponents import SpeedLabel
